deb packages: add wider range of supported libs to run on more targets
- supported (tested) os versions: Ubuntu 22.04. 24.04. + Debian 12 13

- reflect SETUP.md min version requirements

- libsqlite3-0 lower version requirement: 3.37.2

- 22.04 as build env for lower glibc version

- disable explicit packages

- add install tests

- use script for installation

- add systemd

- use systemd container

- switch to podman to allow installation and test

- enable systemd in default images

- remove ubuntu-22.04-packaging-aarch64-static.yml as this is now covered with the dynamic packages

- add armv7 version

- Merge 3 deb packaging workflows in one

- check if so libs are found after installation, before uninstall

- Build with ubuntu 22.04 to link against an older glibc version

- speedup arm32 by using arm64 runner - great improvement

- do not support static builds, remove workflows and files

- change base image in the container file

- adjust curl version to what is minimal available

- remove libzip5 as this is not compatible

- add libzip4 static build as not binary abi compatible to libzip5, the only version available on Debian 13

- Added z (the zlib library) to the linking dependencies for the ggl-zip module. This should resolve the undefined reference to zlib symbols when using static libzip.

- make a parameterized dockerfile to test, for code de-duplication

- separate caching for tests